name: asl-v_3
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - colorama==0.4.6
      - comtypes==1.4.15
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mediapipe==0.10.9
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - openai==2.15.0
      - opencv-contrib-python==4.13.0.90
      - opencv-python==4.13.0.90
      - packaging==26.0
      - pandas==2.3.3
      - pillow==12.1.0
      - protobuf==3.20.3
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.2
      - pypiwin32==223
      - python-dateutil==2.9.0.post0
      - pyttsx3==2.99
      - pytz==2025.2
      - pywin32==311
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - sounddevice==0.5.5
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.10.0
      - torchsummary==1.5.1
      - torchvision==0.25.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - zipp==3.23.0
